#!/usr/bin/env bash

set -e

echo "making release"

prev_version=$(cat mix.exs| grep "version: " | sed -e 's/.*version: "\(.*\)",/\1/')

if [ "$prev_version" == "" ]
then
    minor="1"
else
    prev_minor=$(echo "$prev_version" | cut -d . -f 2)
    minor=$((prev_minor+1))
fi

major=$(echo $prev_version| awk '{ print substr($1, 0, index($1, ".")) }')

version="$major.$minor.0"

echo "updating version in mix file from ${prev_version} to ${version}"

if [ "$prev_version" == "" ]
then
    echo "no prev version.. skipping"
else
    sed -i '' -e "/version/s/${prev_version/v/}/${version/v/}/g" mix.exs
fi

git add mix.exs
git commit -m "Update version in mix.exs to ${version/v/}"
git push origin master

echo "set tag"

git tag "v$version"
git push --tags