#!/usr/bin/env bash

set -e

echo "making release"

if [[ "$OSTYPE" == "linux-gnu" ]];
then
    echo "We are on linux. Starting"
    major=$(cat mix.exs | sed -re 's/version: "([0-9]*)\.([0-9]*)\.([0-9]*)",/\1/g')
    minor=$(cat mix.exs | sed -re 's/version: "([0-9]*)\.([0-9]*)\.([0-9]*)",/\2/g')
    patch=$(cat mix.exs | sed -re 's/version: "([0-9]*)\.([0-9]*)\.([0-9]*)",/\3/g')

    if [ "$patch" == "" ]
    then
        next_patch="0"
    else
        next_patch=$((patch+1))
    fi

    echo "Updating version in mix file from ${major}.${minor}.${patch} to ${major}.${minor}.${next_patch}"

    if [ "$major.$minor.$patch" == ".." ]
    then
        echo "no prev version.. skipping"
    else
        sed -i "/version/s/$major.$minor.$patch/$major.$minor.$next_patch/g" mix.exs
    fi

    echo "Pushing git tag:"

    git add mix.exs
    git commit -m "Update version in mix.exs to $major.$minor.$patch/v/}"
    git push origin master

    git tag "v$major.$minor.$patch"
    git push --tags
elif [[ "$OSTYPE" == "darwin"* ]];
then
    prev_version=$(cat mix.exs| grep "version: " | sed -e 's/.*version: "\(.*\)",/\1/')

    if [ "$prev_version" == "" ]
    then
        patch="0"
    else
        prev_patch=$(echo "$prev_version" | cut -d . -f 3)
        patch=$((prev_patch+1))
    fi

    minor=$(echo $prev_version| awk '{ print substr($1, 0, index($1, ".")+1) }')

    version="$minor.$patch"

    echo "updating version in mix file from ${prev_version} to ${version}"

    if [ "$prev_version" == "" ]
    then
        echo "no prev version.. skipping"
    else
        sed -i '' -e "/version/s/${prev_version/v/}/${version/v/}/g" mix.exs
    fi

    git add mix.exs
    git commit -m "Update version in mix.exs to ${version/v/}"
    git push origin master

    echo "set tag"

    git tag "v$version"
    git push --tags
elif [[ "$OSTYPE" == "msys" ]];
then
    echo "We are on Windows. Starting"
else
    echo "We are on dishwasher. Can't start"
fi
