#!/usr/bin/env bash

set -e

echo "making release"

prev_version=$(cat mix.exs| grep "version: " | sed -e 's/.*version: "\(.*\)",/\1/')

if [ "$prev_version" == "" ]
then
    patch="0"
else
    prev_patch=$(echo "$prev_version" | cut -d . -f 3)
    patch=$((prev_patch+1))
fi

minor=$(echo $prev_version| awk '{ print substr($1, 0, index($1, ".")+1) }')

version="$minor.$patch"

echo "updating version in mix file from ${prev_version} to ${version}"

if [ "$prev_version" == "" ]
then
    echo "no prev version.. skipping"
else
    sed -i '' -e "/version/s/${prev_version/v/}/${version/v/}/g" mix.exs
fi

git add mix.exs
git commit -m "Update version in mix.exs to ${version/v/}"
git push origin master

echo "set tag"

git tag "v$version"
git push --tags